services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: areyoudead
      POSTGRES_USER: areyoudead
      POSTGRES_PASSWORD: areyoudead
    ports:
      - "5432:5432"
    volumes:
      - areyoudead_pgdata:/var/lib/postgresql/data

  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://postgres:5432/areyoudead -user=areyoudead -password=areyoudead -connectRetries=60 migrate
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    depends_on:
      - postgres

volumes:
  areyoudead_pgdata:

